global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using System.Collections.Generic;
global using System.Linq;
global using DD_Dungeons_Destiny;
global using Microsoft.Xna.Framework.Content;
global using System;
global using Drag;